# Generated by Django 6.0.2 on 2026-02-06 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('icon', models.CharField(choices=[('💰', 'Money'), ('💼', 'Work'), ('🏠', 'Home'), ('🍔', 'Food'), ('🚗', 'Transport'), ('🎮', 'Entertainment'), ('🏥', 'Health'), ('📚', 'Education'), ('🛒', 'Shopping'), ('✈️', 'Travel'), ('💡', 'Utilities'), ('📱', 'Phone'), ('🎁', 'Gifts'), ('💳', 'Subscriptions'), ('📈', 'Investments'), ('🏦', 'Banking'), ('👨\u200d👩\u200d👧', 'Family'), ('🐕', 'Pets'), ('💇', 'Personal Care'), ('📦', 'Other')], default='📦', max_length=10)),
                ('color', models.CharField(default='#4F46E5', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['type', 'name'],
                'unique_together': {('user', 'name', 'type')},
            },
        ),
    ]
