# Generated by Django 6.0.2 on 2026-02-06 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('spending_analysis', 'Spending Analysis'), ('savings_tip', 'Savings Tip'), ('anomaly_alert', 'Anomaly Alert'), ('budget_recommendation', 'Budget Recommendation'), ('category_suggestion', 'Category Suggestion')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('transaction_id', models.IntegerField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat History',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpendingAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('unusual_amount', 'Unusual Amount'), ('unusual_category', 'Unusual Category'), ('unusual_frequency', 'Unusual Frequency'), ('duplicate', 'Possible Duplicate')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('description', models.TextField()),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deviation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spending Anomaly',
                'verbose_name_plural': 'Spending Anomalies',
                'ordering': ['-created_at'],
            },
        ),
    ]
